import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
            href="https://fonts.googleapis.com/css2?family=Poppins:wght@700&display=swap"
            rel="stylesheet"
          />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Hi, I'm Quaven and I
        </h1>
        <h1 className={styles.title}>
          Design things for a living.
        </h1>
        <h1 className={styles.title}>
          Website Launching Soon.
        </h1>
      </main>
    </div>
  )
}
